# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import bi_directional_stream_pb2 as protos_dot_bi__directional__stream__pb2


class BiDirectionalStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.bi_direction_stream = channel.stream_stream(
                '/birectional_stream.BiDirectionalStream/bi_direction_stream',
                request_serializer=protos_dot_bi__directional__stream__pb2.ClientRequest.SerializeToString,
                response_deserializer=protos_dot_bi__directional__stream__pb2.ServerResponse.FromString,
                )


class BiDirectionalStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def bi_direction_stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BiDirectionalStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'bi_direction_stream': grpc.stream_stream_rpc_method_handler(
                    servicer.bi_direction_stream,
                    request_deserializer=protos_dot_bi__directional__stream__pb2.ClientRequest.FromString,
                    response_serializer=protos_dot_bi__directional__stream__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'birectional_stream.BiDirectionalStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BiDirectionalStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def bi_direction_stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/birectional_stream.BiDirectionalStream/bi_direction_stream',
            protos_dot_bi__directional__stream__pb2.ClientRequest.SerializeToString,
            protos_dot_bi__directional__stream__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
