# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/bi_directional_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protos/bi_directional_stream.proto\x12\x12\x62irectional_stream\"(\n\rClientRequest\x12\x17\n\x0frequest_message\x18\x01 \x01(\t\"A\n\x0eServerResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x18\n\x10response_message\x18\x02 \x01(\t2y\n\x13\x42iDirectionalStream\x12\x62\n\x13\x62i_direction_stream\x12!.birectional_stream.ClientRequest\x1a\".birectional_stream.ServerResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_CLIENTREQUEST = DESCRIPTOR.message_types_by_name['ClientRequest']
_SERVERRESPONSE = DESCRIPTOR.message_types_by_name['ServerResponse']
ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'protos.bi_directional_stream_pb2'
  # @@protoc_insertion_point(class_scope:birectional_stream.ClientRequest)
  })
_sym_db.RegisterMessage(ClientRequest)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'protos.bi_directional_stream_pb2'
  # @@protoc_insertion_point(class_scope:birectional_stream.ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)

_BIDIRECTIONALSTREAM = DESCRIPTOR.services_by_name['BiDirectionalStream']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTREQUEST._serialized_start=58
  _CLIENTREQUEST._serialized_end=98
  _SERVERRESPONSE._serialized_start=100
  _SERVERRESPONSE._serialized_end=165
  _BIDIRECTIONALSTREAM._serialized_start=167
  _BIDIRECTIONALSTREAM._serialized_end=288
# @@protoc_insertion_point(module_scope)
