# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/client_stream.proto\x12\rclient_stream\"0\n\x16\x43lientStreamingRequest\x12\x16\n\x0e\x63lient_message\x18\x01 \x01(\t\"?\n\rUnaryResponse\x12\x15\n\rresponse_code\x18\x01 \x01(\x05\x12\x17\n\x0fresponse_status\x18\x02 \x01(\t2i\n\x0c\x43lientStream\x12Y\n\x0estream_request\x12%.client_stream.ClientStreamingRequest\x1a\x1c.client_stream.UnaryResponse\"\x00(\x01\x62\x06proto3')



_CLIENTSTREAMINGREQUEST = DESCRIPTOR.message_types_by_name['ClientStreamingRequest']
_UNARYRESPONSE = DESCRIPTOR.message_types_by_name['UnaryResponse']
ClientStreamingRequest = _reflection.GeneratedProtocolMessageType('ClientStreamingRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTSTREAMINGREQUEST,
  '__module__' : 'protos.client_stream_pb2'
  # @@protoc_insertion_point(class_scope:client_stream.ClientStreamingRequest)
  })
_sym_db.RegisterMessage(ClientStreamingRequest)

UnaryResponse = _reflection.GeneratedProtocolMessageType('UnaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNARYRESPONSE,
  '__module__' : 'protos.client_stream_pb2'
  # @@protoc_insertion_point(class_scope:client_stream.UnaryResponse)
  })
_sym_db.RegisterMessage(UnaryResponse)

_CLIENTSTREAM = DESCRIPTOR.services_by_name['ClientStream']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTSTREAMINGREQUEST._serialized_start=45
  _CLIENTSTREAMINGREQUEST._serialized_end=93
  _UNARYRESPONSE._serialized_start=95
  _UNARYRESPONSE._serialized_end=158
  _CLIENTSTREAM._serialized_start=160
  _CLIENTSTREAM._serialized_end=265
# @@protoc_insertion_point(module_scope)
