# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import client_stream_pb2 as protos_dot_client__stream__pb2


class ClientStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream_request = channel.stream_unary(
                '/client_stream.ClientStream/stream_request',
                request_serializer=protos_dot_client__stream__pb2.ClientStreamingRequest.SerializeToString,
                response_deserializer=protos_dot_client__stream__pb2.UnaryResponse.FromString,
                )


class ClientStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream_request(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream_request': grpc.stream_unary_rpc_method_handler(
                    servicer.stream_request,
                    request_deserializer=protos_dot_client__stream__pb2.ClientStreamingRequest.FromString,
                    response_serializer=protos_dot_client__stream__pb2.UnaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client_stream.ClientStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream_request(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/client_stream.ClientStream/stream_request',
            protos_dot_client__stream__pb2.ClientStreamingRequest.SerializeToString,
            protos_dot_client__stream__pb2.UnaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
