# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/server_stream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aprotos/server_stream.proto\x12\rserver_stream\"$\n\rClientRequest\x12\x13\n\x0breq_message\x18\x01 \x01(\t\"E\n\x14ServerStreamResponse\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x18\n\x10response_message\x18\x02 \x01(\t2h\n\x0cServerStream\x12X\n\x0fstream_response\x12\x1c.server_stream.ClientRequest\x1a#.server_stream.ServerStreamResponse\"\x00\x30\x01\x62\x06proto3')



_CLIENTREQUEST = DESCRIPTOR.message_types_by_name['ClientRequest']
_SERVERSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['ServerStreamResponse']
ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'protos.server_stream_pb2'
  # @@protoc_insertion_point(class_scope:server_stream.ClientRequest)
  })
_sym_db.RegisterMessage(ClientRequest)

ServerStreamResponse = _reflection.GeneratedProtocolMessageType('ServerStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERSTREAMRESPONSE,
  '__module__' : 'protos.server_stream_pb2'
  # @@protoc_insertion_point(class_scope:server_stream.ServerStreamResponse)
  })
_sym_db.RegisterMessage(ServerStreamResponse)

_SERVERSTREAM = DESCRIPTOR.services_by_name['ServerStream']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTREQUEST._serialized_start=45
  _CLIENTREQUEST._serialized_end=81
  _SERVERSTREAMRESPONSE._serialized_start=83
  _SERVERSTREAMRESPONSE._serialized_end=152
  _SERVERSTREAM._serialized_start=154
  _SERVERSTREAM._serialized_end=258
# @@protoc_insertion_point(module_scope)
