# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import server_stream_pb2 as protos_dot_server__stream__pb2


class ServerStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stream_response = channel.unary_stream(
                '/server_stream.ServerStream/stream_response',
                request_serializer=protos_dot_server__stream__pb2.ClientRequest.SerializeToString,
                response_deserializer=protos_dot_server__stream__pb2.ServerStreamResponse.FromString,
                )


class ServerStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stream_response(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stream_response': grpc.unary_stream_rpc_method_handler(
                    servicer.stream_response,
                    request_deserializer=protos_dot_server__stream__pb2.ClientRequest.FromString,
                    response_serializer=protos_dot_server__stream__pb2.ServerStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_stream.ServerStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stream_response(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/server_stream.ServerStream/stream_response',
            protos_dot_server__stream__pb2.ClientRequest.SerializeToString,
            protos_dot_server__stream__pb2.ServerStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
