# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.protos import unary_pb2 as protos_dot_unary__pb2


class UnaryStub(object):
    """Single-Request | Single-Response
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.invoke_server = channel.unary_unary(
                '/unary.Unary/invoke_server',
                request_serializer=protos_dot_unary__pb2.InitiateRequest.SerializeToString,
                response_deserializer=protos_dot_unary__pb2.FetchResponse.FromString,
                )


class UnaryServicer(object):
    """Single-Request | Single-Response
    """

    def invoke_server(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'invoke_server': grpc.unary_unary_rpc_method_handler(
                    servicer.invoke_server,
                    request_deserializer=protos_dot_unary__pb2.InitiateRequest.FromString,
                    response_serializer=protos_dot_unary__pb2.FetchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Unary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Unary(object):
    """Single-Request | Single-Response
    """

    @staticmethod
    def invoke_server(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/invoke_server',
            protos_dot_unary__pb2.InitiateRequest.SerializeToString,
            protos_dot_unary__pb2.FetchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
