# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/unary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/unary.proto\x12\x05unary\"\x1e\n\x0fInitiateRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"*\n\rFetchResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x0c\n\x04rcvd\x18\x02 \x01(\x08\x32H\n\x05Unary\x12?\n\rinvoke_server\x12\x16.unary.InitiateRequest\x1a\x14.unary.FetchResponse\"\x00\x62\x06proto3')



_INITIATEREQUEST = DESCRIPTOR.message_types_by_name['InitiateRequest']
_FETCHRESPONSE = DESCRIPTOR.message_types_by_name['FetchResponse']
InitiateRequest = _reflection.GeneratedProtocolMessageType('InitiateRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITIATEREQUEST,
  '__module__' : 'protos.unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.InitiateRequest)
  })
_sym_db.RegisterMessage(InitiateRequest)

FetchResponse = _reflection.GeneratedProtocolMessageType('FetchResponse', (_message.Message,), {
  'DESCRIPTOR' : _FETCHRESPONSE,
  '__module__' : 'protos.unary_pb2'
  # @@protoc_insertion_point(class_scope:unary.FetchResponse)
  })
_sym_db.RegisterMessage(FetchResponse)

_UNARY = DESCRIPTOR.services_by_name['Unary']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIATEREQUEST._serialized_start=29
  _INITIATEREQUEST._serialized_end=59
  _FETCHRESPONSE._serialized_start=61
  _FETCHRESPONSE._serialized_end=103
  _UNARY._serialized_start=105
  _UNARY._serialized_end=177
# @@protoc_insertion_point(module_scope)
